//
//  BlocksLayer.h
//  RedCore
//

#ifndef Paddle_h
#define Paddle_h

#include "cocos2d.h"

#define HALF 1
#define NORMAL 2
#define DOUBLE 3

class Paddle : public cocos2d::Node {
    public:
        virtual bool init();
        void doubleSize();
        void halfSize();
        void listen(double width); // começa escutar eventos do touch
        CREATE_FUNC(Paddle);
    private:
        cocos2d::DrawNode* double_paddle;
        cocos2d::DrawNode* normal_paddle;
        cocos2d::DrawNode* half_paddle;
        int stade; // armaze em que tamanho esta
        void setPX (double px, double width); // arruma a posicao de todas as raquetes
        void normalSize();
        void startNormalTimer(); // Inicia o timer para voltar ao normal

};

#endif /* Paddle_h */
